In [1]:
from tools import *
import numpy as np

In [2]:
PATH_TO_LVK_DATA = '/Users/ulyana/Documents/GSSI/PhD Projects/GWTC_analysis/GWTC_LVK_data/'
PATH_TO_RESULTS = '/Users/ulyana/Documents/GSSI/PhD Projects/GWTC_analysis/'
PATH_TO_YAML = '/Users/ulyana/Documents/GSSI/PhD Projects/GWTC_analysis/yaml/'
PATH_TO_PSD = '/Users/ulyana/Documents/GSSI/PhD Projects/GWTC_analysis/gwtc_psds/'

In [3]:
waveform = 'IMRPhenomXPHM'

## Select events and create injections for GWFish

In [3]:
estimator = 'maxP' # or 'median
params = ['chirp_mass', 'mass_ratio', 'mass_1', 'mass_2', 'luminosity_distance', 'dec', 'ra', 'theta_jn', 'psi', 'phase', 
            'geocent_time', 'a_1', 'a_2', 'tilt_1', 'tilt_2', 'phi_12', 'phi_jl', 'redshift']

In [4]:
create_injections_from_gwtc(PATH_TO_LVK_DATA, PATH_TO_RESULTS, waveform, params, estimator)

PyCBC.libutils: pkg-config call failed, setting NO_PKGCONFIG=1


In [7]:
# Intersect the injectiosn with median and maxP
median_list = np.loadtxt(PATH_TO_RESULTS + 'info/event_list_%s_%s.txt' %(waveform, 'median'), dtype=str)
maxP_list = np.loadtxt(PATH_TO_RESULTS + 'info/event_list_%s_%s.txt' %(waveform, 'maxP'), dtype=str)
median_maxP_intersection_list = list(set(maxP_list).intersection(median_list))
np.savetxt(PATH_TO_RESULTS + 'info/event_list_intersection_%s_%s.txt' %(waveform, 'median_maxP'), median_maxP_intersection_list, fmt='%s')


In [5]:
# Select events that have an analytical prior
events_maxP_median = np.loadtxt(PATH_TO_RESULTS + 'info/event_list_intersection_%s_median_maxP.txt' %(waveform), dtype=str)
check_and_store_priors(PATH_TO_LVK_DATA, PATH_TO_RESULTS, events_maxP_median, waveform)

## List of rejected events

### Events rejected because not BBH 

Therefore, they are not analyzed using the waveform approximant IMRPhenomXPHM

In [8]:
no_imrphenomxphm = np.loadtxt(PATH_TO_RESULTS + 'info/waveform_not_in_list_IMRPhenomXPHM.txt', dtype=str)
print(no_imrphenomxphm)

['IGWN-GWTC3p0-v2-GW200105_162426_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC2p1-v2-GW190425_081805_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC3p0-v2-GW191219_163120_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC3p0-v2-GW200115_042309_PEDataRelease_mixed_cosmo']


### Events rejected because do no have a maxP estimate

In [9]:
no_maxP = np.loadtxt(PATH_TO_RESULTS + 'info/maxP_not_in_list_for_%s.txt' %waveform, dtype=str)
print(no_maxP)

['IGWN-GWTC3p0-v2-GW191126_115259_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC3p0-v2-GW200306_093714_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC3p0-v2-GW200308_173609_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC3p0-v2-GW191216_213338_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC3p0-v2-GW200316_215756_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC3p0-v2-GW191113_071753_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC3p0-v2-GW200322_091133_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC3p0-v2-GW191129_134029_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC3p0-v2-GW200220_124850_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC3p0-v2-GW200210_092254_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC3p0-v2-GW191204_171526_PEDataRelease_mixed_cosmo']


### Events rejected because they do not provide an analytic prior

In [10]:
no_prior = np.loadtxt(PATH_TO_RESULTS + 'info/events_with_no_priors_%s.txt' %waveform, dtype=str)
print(no_prior)

['IGWN-GWTC2p1-v2-GW190917_114630_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC2p1-v2-GW190814_211039_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC2p1-v2-GW190924_021846_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC2p1-v2-GW170608_020116_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC2p1-v2-GW190728_064510_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC2p1-v2-GW190707_093326_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC2p1-v2-GW190720_000836_PEDataRelease_mixed_cosmo'
 'IGWN-GWTC2p1-v2-GW190725_174728_PEDataRelease_mixed_cosmo']


## Create .yaml files and store detectors information

In [4]:
events = np.loadtxt(PATH_TO_RESULTS + 'info/' + 'events_with_priors_%s.txt' %waveform, dtype=str)

In [5]:
detectors_and_yaml_files(PATH_TO_LVK_DATA, PATH_TO_RESULTS, PATH_TO_YAML, PATH_TO_PSD, events, waveform)

## Fisher Analysis

In [4]:
events = np.loadtxt(PATH_TO_RESULTS + 'info/' + 'events_with_priors_%s.txt' %waveform, dtype=str)
with open(PATH_TO_RESULTS + 'info/' + 'detectors_dictionary.pkl', 'rb') as f:
    detectors = pickle.load(f)

In [8]:
estimator = 'median'
waveform = 'IMRPhenomXPHM'
fisher_parameters = ['mass_1', 'mass_2', 'luminosity_distance', 'dec', 'ra', 'theta_jn', 'psi', 'phase', 
            'geocent_time', 'a_1', 'a_2', 'tilt_1', 'tilt_2', 'phi_12', 'phi_jl']
gw.fishermatrix.gwfish_analysisgwfish_analysis(PATH_TO_YAML, PATH_TO_RESULTS + '/injections/', events, waveform, estimator,
                    detectors, fisher_parameters, PATH_TO_RESULTS + '/results/gwfish_m1_m2/')

  0%|          | 0/67 [00:00<?, ?it/s]

100%|██████████| 67/67 [18:15<00:00, 16.36s/it]


In [9]:
!mv Sing_* '../GWTC_analysis/results/gwfish_m1_m2_from_mChirp_q/sing_values/'
!mv Errors* '../GWTC_analysis/results/gwfish_m1_m2_from_mChirp_q/errors/'
!mv Fishers* '../GWTC_analysis/results/gwfish_m1_m2_from_mChirp_q/fishers/'
!mv Inv_Fishers* '../GWTC_analysis/results/gwfish_m1_m2_from_mChirp_q/inv_fishers/'
!mv Signals* '../GWTC_analysis/results/gwfish_m1_m2_from_mChirp_q/signals/'

## Test

In [4]:
fisher_parameters = ['mass_1', 'mass_2', 'luminosity_distance', 'dec', 'ra', 'theta_jn', 'psi', 'phase', 
            'geocent_time', 'a_1', 'a_2', 'tilt_1', 'tilt_2', 'phi_12', 'phi_jl']

In [24]:
k=10

In [25]:
estimator = 'median'
events = np.loadtxt(PATH_TO_RESULTS + 'info/' + 'events_with_priors_%s.txt' %waveform, dtype=str)
with open(PATH_TO_RESULTS + 'info/' + 'detectors_dictionary.pkl', 'rb') as f:
    detectors = pickle.load(f)

In [26]:
detectors_labels = list(detectors[events[k]])
connector = '_'
label = detectors_labels[0]
for i in range(1, len(detectors_labels)):
    label += connector + detectors_labels[i]
label


'H1_L1_V1'

In [27]:
# get fishers
fishers = np.load(PATH_TO_RESULTS + 'results/gwfish_m1_m2_from_mChirp_q/fishers/' + 'Fishers_%s_%s_BBH_%s_SNR1.0.npy' %(label, estimator, events[k]))
my_fish = fishers[0, :, :]
my_fish

array([[ 1.31805660e+00,  1.00469314e+00, -1.65290365e-04, ...,
         1.15754616e+01,  4.71799615e+00, -4.24398494e-01],
       [ 1.00469314e+00,  1.07122146e+00, -4.50378532e-04, ...,
         7.13649007e+00,  7.41651703e-01, -5.39648518e-01],
       [-1.65290365e-04, -4.50378532e-04,  1.22227015e-05, ...,
         1.64507844e-03,  3.43064745e-03,  6.57760260e-04],
       ...,
       [ 1.15754616e+01,  7.13649007e+00,  1.64507844e-03, ...,
         1.14987944e+02,  5.89457493e+01, -2.87508867e+00],
       [ 4.71799615e+00,  7.41651703e-01,  3.43064745e-03, ...,
         5.89457493e+01,  4.71705249e+01,  6.66909992e-01],
       [-4.24398494e-01, -5.39648518e-01,  6.57760260e-04, ...,
        -2.87508867e+00,  6.66909992e-01,  1.08415421e+00]])

In [28]:
import pandas as pd

In [29]:
lbs = ['chirp_mass', 'mass_ratio', 'mass_1', 'mass_2', 'luminosity_distance', 'dec', 'ra', 'theta_jn', 'psi', 'phase',\
         'geocent_time', 'a_1', 'a_2', 'tilt_1', 'tilt_2', 'phi_12', 'phi_jl', 'redshift', 'mass1_lvk', 'mass2_lvk', 'snr']

In [30]:
signals = pd.read_csv(PATH_TO_RESULTS + 'results/gwfish_m1_m2_from_mChirp_q/signals/' + 'Signals_%s_BBH_%s.txt' %(estimator, events[k]), names = lbs, skiprows = 1, delimiter = ' ')

In [31]:
m1, m2 = signals[['mass_1', 'mass_2']].iloc[0]


In [32]:
m1

42.35298604183378

In [33]:
rotated_fisher = jacobian_for_derivative_from_m1_m2_to_mChirp_q(m1, m2, fishers)

In [34]:
rotated_fisher

array([[[ 2.39714535e+00,  4.78213022e+01, -2.22909045e-04,
         ...,  1.56105597e+01,  6.36264563e+00,
         -5.72339853e-01],
        [ 4.78213022e+01,  1.33442717e+03, -1.58959134e-02,
         ...,  2.51879297e+02,  2.61762726e+01,
         -1.90466585e+01],
        [-2.22909045e-04, -1.58959134e-02,  1.22227015e-05,
         ...,  1.64507844e-03,  3.43064745e-03,
          6.57760260e-04],
        ...,
        [ 1.56105597e+01,  2.51879297e+02,  1.64507844e-03,
         ...,  1.14987944e+02,  5.89457493e+01,
         -2.87508867e+00],
        [ 6.36264563e+00,  2.61762726e+01,  3.43064745e-03,
         ...,  5.89457493e+01,  4.71705249e+01,
          6.66909992e-01],
        [-5.72339853e-01, -1.90466585e+01,  6.57760260e-04,
         ..., -2.87508867e+00,  6.66909992e-01,
          1.08415421e+00]]])

In [35]:
import GWFish.modules as gw

In [36]:
inv_rotated_fisher, sing_values = gw.fishermatrix.invertSVD(rotated_fisher[0, :, :])

In [37]:
inv_rotated_fisher

array([[ 5.42006968e+01, -1.20051177e+00,  1.66589896e+02, ...,
         3.80796078e+00,  8.77468396e-01, -1.42945520e+00],
       [-1.20051177e+00,  5.79887395e-02,  4.23649082e+01, ...,
        -2.42593743e-01, -2.20969048e-02,  2.15807276e-02],
       [ 1.66589896e+02,  4.23649082e+01,  2.36114632e+05, ...,
        -4.71559551e+02,  6.56575523e+01, -3.12018332e+01],
       ...,
       [ 3.80796078e+00, -2.42593743e-01, -4.71559551e+02, ...,
         5.67186345e+00, -2.70694031e-02,  4.30847659e-01],
       [ 8.77468396e-01, -2.20969048e-02,  6.56575523e+01, ...,
        -2.70694031e-02,  2.64530539e+00, -1.19426198e+00],
       [-1.42945520e+00,  2.15807276e-02, -3.12018332e+01, ...,
         4.30847659e-01, -1.19426198e+00,  4.65129234e+00]])

In [38]:
print(np.sqrt(np.diagonal(inv_rotated_fisher)))

[7.36211225e+00 2.40808512e-01 4.85916281e+02 2.85193726e-01
 4.80689589e-01 2.91091213e-01 4.13489773e-01 6.64048860e-01
 5.25167962e-03 8.23878305e-01 9.17547402e-01 1.31190035e+00
 2.38156744e+00 1.62643948e+00 2.15668550e+00]


In [39]:
cov = np.load(PATH_TO_RESULTS + 'results/gwfish_m1_m2_from_mChirp_q/inv_fishers/' + 'Inv_Fishers_%s_%s_BBH_%s_SNR1.0.npy' %(label, estimator, events[k]))

In [40]:
np.sqrt(np.diagonal(cov[0, :, :]))

array([9.92847596e+00, 8.49923115e+00, 4.85916281e+02,
       2.85193726e-01, 4.80689589e-01, 2.91091213e-01,
       4.13489773e-01, 6.64048860e-01, 5.25167962e-03,
       8.23878305e-01, 9.17547402e-01, 1.31190035e+00,
       2.38156744e+00, 1.62643948e+00, 2.15668550e+00])

In [41]:
events[k]

'IGWN-GWTC2p1-v2-GW190915_235702_PEDataRelease_mixed_cosmo'

## Rotate Fisher matrix from m1-m2 to mChirp and q

In [4]:
estimator = 'median'
events = np.loadtxt(PATH_TO_RESULTS + 'info/' + 'events_with_priors_%s.txt' %waveform, dtype=str)
with open(PATH_TO_RESULTS + 'info/' + 'detectors_dictionary.pkl', 'rb') as f:
    detectors = pickle.load(f)

In [5]:
lbs_signals = ['chirp_mass', 'mass_ratio', 'mass_1', 'mass_2', 'luminosity_distance', 'dec', 'ra', 'theta_jn', 'psi', 'phase',\
         'geocent_time', 'a_1', 'a_2', 'tilt_1', 'tilt_2', 'phi_12', 'phi_jl', 'redshift', 'mass1_lvk', 'mass2_lvk', 'snr']

In [6]:
lbs_errs = ['snr', 'chirp_mass', 'mass_ratio', 'mass_1', 'mass_2', 'luminosity_distance', 'dec', 'ra', 'theta_jn',
        'psi', 'phase', 'geocent_time', 'a_1', 'a_2', 'tilt_1', 'tilt_2', 'phi_12', 'phi_jl', 'redshift', 
        'mass1_lvk', 'mass2_lvk', 'err_mass_1', 'err_mass_2', 'err_luminosity_distance', 'err_dec', 'err_ra',
        'err_theta_jn', 'err_psi', 'err_phase', 'err_geocent_time', 'err_a_1', 'err_a_2', 'err_tilt_1',
        'err_tilt_2', 'err_phi_12', 'err_phi_jl', 'err_sky_location']

In [7]:
new_fisher_parameters = ['chirp_mass', 'mass_ratio', 'luminosity_distance', 'dec', 'ra', 'theta_jn', 'psi', 'phase',
            'geocent_time', 'a_1', 'a_2', 'tilt_1', 'tilt_2', 'phi_12', 'phi_jl']

In [8]:
get_rotated_fisher_matrix(PATH_TO_RESULTS, PATH_TO_RESULTS, events, detectors, 
                          estimator, lbs_signals, lbs_errs, new_fisher_parameters)

## Apply priors